### ISSUE TITLE
Critical Error "The address is not in the database"

### ISSUE THREAD

**Issue by SuN-80** [maxmind/GeoIP2-php#116] opened 2018-06-22 07:39 UTC
Here is the message that I found multiple times in my logs: `The address 10.3.3.9 is not in the database`
Error is generated in /geoip2/geoip2/src/Database/Reader.php' at line 244

I guess that's what will happen for any IP not in DB. I don't understand why it doe snot return an unknown location instead.

For the record such an issue was reported in #103, but in my case it's not a reserved IP that produced the error.

**Comment by ChadTaljaardt** [comment] 2018-06-22 07:53
Dupe of : 

https://github.com/maxmind/GeoIP2-php/issues/105
https://github.com/maxmind/GeoIP2-php/issues/17

**Closed** 2018-06-22 08:04 UTC

**Comment by SuN-80** [comment] 2018-06-22 08:44
Oh boy, my bad. Thanks @ChadTaljaardt 

Throwing an exception on error is great, but I wonder why it's not implemented in the main examples. Because sample code will generate such a critical error... Unless GeoIP is a core dependency in your app, it does not make sense to get a critical error for this in case you forgot to handle the exception.
