### ISSUE TITLE
T_CONSTANT_ENCAPSED_STRING on `use GeoIp2\WebService\Client;`

### ISSUE THREAD

**Issue by carlosfcocruz** [maxmind/GeoIP2-php#86] opened 2016-11-06 05:19 UTC
It works on my local environment, but when I deploy to my server, I'm getting `T_CONSTANT_ENCAPSED_STRING`. Any tips ?

**Comment by oschwald** [comment] 2016-11-07 15:07
It sounds like there is a syntax error in the calling code. Could you provide that?

Also, what version of PHP is on the server?

**Comment by oschwald** [comment] 2016-11-21 22:02
I am closing this as I cannot reproduce it without more information.

**Closed by oschwald** 2016-11-21 22:02 UTC
