### ISSUE TITLE
cURL error (77): error setting certificate verify locations:

### ISSUE THREAD

**Issue by lfjeff** [maxmind/GeoIP2-php#134] opened 2019-08-01 00:04 UTC
Lately, I've been getting this error:
`Uncaught MaxMind\Exception\HttpException: cURL error (77): error setting certificate verify locations:`

I've tried downloading certs from `http://curl.haxx.se/ca/cacert.pem` and installing them on my Ubuntu 16.04 system in `/etc/ssl/certs`, but it does not fix the problem.

I've also tried setting `curl.cainfo="/etc/ssl/certs/cacert.pem"` in my `php.ini` and that makes no difference.

If I edit the `MaxMind\Webservice\Http\CurlRequest.php` file and set `CURLOPT_SSL_VERIFYPEER` to false, it starts working again.  However, this is not the best solution.

**Comment by dwightwatson** [comment] 2019-08-01 00:33
Started seeing this in production about 24 hours ago (on Heroku). 

Not able to reproduce locally.

**Comment by oschwald** [comment] 2019-08-01 03:19
What version of `composer/ca-bundle` do you have? It looks like there was an issue in 1.2.0 that was fixed in 1.2.1. https://github.com/composer/ca-bundle/issues/44

**Comment by exussum12** [comment] 2019-08-01 09:56
There should be another fix for 1.2.2 can you try this please ?

**Comment by oschwald** [comment] 2019-08-01 15:28
Given that this is an issue in a dependency and it appears to be fixed, I am going to close this. However, please let us know if the issue persists after upgrading to 1.2.2.

**Comment by dwightwatson** [comment] 2019-08-01 15:46
I'm still experiencing this issue after upgrading to 1.2.2.

**Comment by lfjeff** [comment] 2019-08-01 16:43
Also upgraded to 1.2.2 and have the same issue

**Comment by oschwald** [comment] 2019-08-01 16:48
As a workaround, I'd suggest forcing `composer/ca-bundle` to be 1.1.4. Hopefully this will be fixed upstream soon.

**Comment by lfjeff** [comment] 2019-08-01 17:06
I reverted to ca-bundle 1.1.4 and things are still broken

**Comment by exussum12** [comment] 2019-08-01 17:12
Can someone send me the output of 

openssl_get_cert_locations()

And what ca file / dir comes back from getSystemCaRootBundlePath

**Comment by exussum12** [comment] 2019-08-01 17:18
Is there a public system where this happens that I can debug on ? I can't make this happen locally

**Comment by lfjeff** [comment] 2019-08-01 17:43
```
vardump(openssl_get_cert_locations))
array(8) {
  ["default_cert_file"]=>
  string(21) "/usr/lib/ssl/cert.pem"
  ["default_cert_file_env"]=>
  string(13) "SSL_CERT_FILE"
  ["default_cert_dir"]=>
  string(18) "/usr/lib/ssl/certs"
  ["default_cert_dir_env"]=>
  string(12) "SSL_CERT_DIR"
  ["default_private_dir"]=>
  string(20) "/usr/lib/ssl/private"
  ["default_default_cert_area"]=>
  string(12) "/usr/lib/ssl"
  ["ini_cafile"]=>
  string(0) ""
  ["ini_capath"]=>
  string(0) ""
}
```

**Comment by exussum12** [comment] 2019-08-01 17:49
Does `/usr/lib/ssl/cert.pem` exist and are there loads of files in `/usr/lib/ssl/certs`

running ls -l on both should should you enough info

**Comment by lfjeff** [comment] 2019-08-01 17:59
```
ls -l /usr/lib/ssl/cert.pem
ls: cannot access '/usr/lib/ssl/cert.pem': No such file or directory
```

`/usr/lib/ssl/certs` has lots of files

**Comment by exussum12** [comment] 2019-08-01 18:06
Since 1.2 that directory will be used. I assume it's not got up to date files. Any chance you could zip that directory and post it ?  It should be lots of root CA cert files each one fairly small and named after a company known for SSL eg digicert 

Thanks for the hell debugging

**Comment by lfjeff** [comment] 2019-08-01 18:50
```
lrwxrwxrwx 1 root root     38 Mar 11  2018 244b5494.0 -> DigiCert_High_Assurance_EV_Root_CA.pem
lrwxrwxrwx 1 root root     27 Mar 11  2018 3513523f.0 -> DigiCert_Global_Root_CA.pem
lrwxrwxrwx 1 root root     27 Mar 11  2018 399e7759.0 -> DigiCert_Global_Root_CA.pem
lrwxrwxrwx 1 root root     27 Mar 11  2018 607986c7.0 -> DigiCert_Global_Root_G2.pem
lrwxrwxrwx 1 root root     31 Mar 11  2018 69105f4f.0 -> DigiCert_Assured_ID_Root_CA.pem
lrwxrwxrwx 1 root root     28 Mar 11  2018 75d1b2ed.0 -> DigiCert_Trusted_Root_G4.pem
lrwxrwxrwx 1 root root     31 Mar 11  2018 7f3d5d1d.0 -> DigiCert_Assured_ID_Root_G3.pem
lrwxrwxrwx 1 root root     38 Mar 11  2018 81b9768f.0 -> DigiCert_High_Assurance_EV_Root_CA.pem
lrwxrwxrwx 1 root root     31 Mar 11  2018 8d6437c3.0 -> DigiCert_Assured_ID_Root_G2.pem
lrwxrwxrwx 1 root root     31 Mar 11  2018 9d04f354.0 -> DigiCert_Assured_ID_Root_G2.pem
lrwxrwxrwx 1 root root     28 Mar 11  2018 a2c66da8.0 -> DigiCert_Trusted_Root_G4.pem
lrwxrwxrwx 1 root root     31 Mar 11  2018 b1159c4c.0 -> DigiCert_Assured_ID_Root_CA.pem
lrwxrwxrwx 1 root root     31 Mar 11  2018 c491639e.0 -> DigiCert_Assured_ID_Root_G3.pem
lrwxrwxrwx 1 root root     27 Mar 11  2018 c90bc37d.0 -> DigiCert_Global_Root_G2.pem
lrwxrwxrwx 1 root root     27 Mar 11  2018 dd8e9d41.0 -> DigiCert_Global_Root_G3.pem
lrwxrwxrwx 1 root root     66 Aug 31  2016 DigiCert_Assured_ID_Root_CA.pem -> /usr/share/ca-certificates/mozilla/DigiCert_Assured_ID_Root_CA.crt
lrwxrwxrwx 1 root root     66 Aug 31  2016 DigiCert_Assured_ID_Root_G2.pem -> /usr/share/ca-certificates/mozilla/DigiCert_Assured_ID_Root_G2.crt
lrwxrwxrwx 1 root root     66 Aug 31  2016 DigiCert_Assured_ID_Root_G3.pem -> /usr/share/ca-certificates/mozilla/DigiCert_Assured_ID_Root_G3.crt
lrwxrwxrwx 1 root root     62 Aug 31  2016 DigiCert_Global_Root_CA.pem -> /usr/share/ca-certificates/mozilla/DigiCert_Global_Root_CA.crt
lrwxrwxrwx 1 root root     62 Aug 31  2016 DigiCert_Global_Root_G2.pem -> /usr/share/ca-certificates/mozilla/DigiCert_Global_Root_G2.crt
lrwxrwxrwx 1 root root     62 Aug 31  2016 DigiCert_Global_Root_G3.pem -> /usr/share/ca-certificates/mozilla/DigiCert_Global_Root_G3.crt
lrwxrwxrwx 1 root root     73 Aug 31  2016 DigiCert_High_Assurance_EV_Root_CA.pem -> /usr/share/ca-certificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.crt
lrwxrwxrwx 1 root root     63 Aug 31  2016 DigiCert_Trusted_Root_G4.pem -> /usr/share/ca-certificates/mozilla/DigiCert_Trusted_Root_G4.crt
lrwxrwxrwx 1 root root     27 Mar 11  2018 ed39abd0.0 -> DigiCert_Global_Root_G3.pem
```

**Comment by lfjeff** [comment] 2019-08-01 18:56
Here's a file with all the certs
[certs.zip](https://github.com/maxmind/GeoIP2-php/files/3458252/certs.zip)

**Comment by exussum12** [comment] 2019-08-01 20:03
struggeling to replicate.

Have you got an example URL ?

Script I am using as follows

```

<?php
$curl = curl_init("https://your.url");

curl_setopt($curl, CURLOPT_CAPATH, '/tmp/certs/');
curl_setopt($curl, CURLOPT_VERBOSE, true);

$result = curl_exec($curl);
var_dump($result);

```

This works on all of the URLs i tried. /tmp/certs is the files extracted from your zip.

Does this work on the URL you are accessing ?

**Comment by oschwald** [comment] 2019-08-01 20:28
The host being used is likely `geoip.maxmind.com`. The curl setup is [here](https://github.com/maxmind/web-service-common-php/blob/master/src/WebService/Http/CurlRequest.php#L56).

**Comment by exussum12** [comment] 2019-08-01 20:30
Thanks. Think I've found the issue. Thanks both for the support :)

**Comment by nmann4789** [comment] 2019-08-02 09:31
@exussum12 I'm still experiencing this issue as well, what did you do to fix it?

**Comment by exussum12** [comment] 2019-08-02 09:59
If you update to 1.2.3 (just been released) it should be resolved. Sorry for the inconvenience the feature added was to get the certificates from  openssl itself. It seems that its not reliable to use what openssl suggests

**Comment by oschwald** [comment] 2019-08-02 14:21
Thanks, @exussum12! I will close this issue again.

**Closed by oschwald** 2019-08-02 14:21 UTC

**Comment by lfjeff** [comment] 2019-08-02 16:20
I can confirm the version 1.2.3 fixes the problem. Thanks for the fast work.
