### ISSUE TITLE
"The MaxMind DB file's search tree is corrupt"

### ISSUE THREAD

**Issue by slince** [maxmind/GeoIP2-php#97] opened 2017-05-27 05:36 UTC
Hi guys.

It is ok on my local matchine(win 10); however it doesn't work on prodcution machine (Centos 7);

Error report:
```

2017-05-27 13:22:46 Error: exception 'MaxMind\Db\Reader\InvalidDatabaseException' with message 'The MaxMind DB file's search tree is corrupt' in /www/slshop/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php:220
Stack trace:
#0 /www/slshop/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php(116): MaxMind\Db\Reader->resolveDataPointer(5046859)
#1 /www/slshop/vendor/geoip2/geoip2/src/Database/Reader.php(242): MaxMind\Db\Reader->get('180.102.221.159')
#2 /www/slshop/vendor/geoip2/geoip2/src/Database/Reader.php(215): GeoIp2\Database\Reader->getRecord('Country', 'Country', '180.102.221.159')
#3 /www/slshop/vendor/geoip2/geoip2/src/Database/Reader.php(88): GeoIp2\Database\Reader->modelFor('Country', 'Country', '180.102.221.159')
#4 /www/slshop/src/Model/Table/VisitorsTable.php(89): GeoIp2\Database\Reader->country('180.102.221.159')

```

**Comment by oschwald** [comment] 2017-05-27 13:56
It sounds like your database is corrupt. Please verify that the MD5 of the file on Cenos matches the one on your Windows machine.

**Comment by oschwald** [comment] 2017-06-12 14:06
Closing as no additional information has been provided and we cannot reproduce it. Please reopen if you are still experiencing it and can provide steps to reproduce.

**Closed by oschwald** 2017-06-12 14:06 UTC

**Comment by codestellar** [comment] 2021-02-05 07:14
I experienced this issue once but unable to reproduce now! The file got corrupted and I had to perform a re-download
